import * as day01 from "./day-01.js";
import input01 from "./input-01.json";
import * as day02 from "./day-02.js";
import input02 from "./input-02.json";
import * as day03 from "./day-03.js";
import input03 from "./input-03.json";
import * as day04 from "./day-04.js";
import input04 from "./input-04.json";
import * as day05 from "./day-05.js";
import input05 from "./input-05.json";

console.log("--- DAY 01 ---");
console.log("--- part 1 ---");
console.log(`solution: ${day01.part1(input01)}\n\n`);
console.log("--- part 2 ---");
console.log(`solution: ${day01.part2(input01)}\n\n`);
console.log("--- DAY 02 ---");
console.log("--- part 1 ---");
console.log(`solution: ${day02.part1(input02)}\n\n`);
console.log("--- part 2 ---");
console.log(`solution: ${day02.part2(input02)}\n\n`);
console.log("--- DAY 03 ---");
console.log("--- part 1 ---");
console.log(`solution: ${day03.part1(input03)}\n\n`);
console.log("--- part 2 ---");
console.log(`solution: ${day03.part2(input03)}\n\n`);
console.log("--- DAY 04 ---");
console.log("--- part 1 ---");
console.log(`solution: ${day04.part1(input04)}\n\n`);
console.log("--- part 2 ---");
console.log(`solution: ${day04.part2(input04)}\n\n`);
console.log("--- DAY 05 ---");
console.log("--- part 1 ---");
console.log(`solution: ${day05.part1(input05)}\n\n`);
console.log("--- part 2 ---");
console.log(`solution: ${day05.part2(input05)}\n\n`);
